export enum AuditEntityType {
  USER = 'USER',
  PROJECT = 'PROJECT',
  TICKET = 'TICKET',
  COMMENT = 'COMMENT',
  TICKET_DEPENDENCY = 'TICKET_DEPENDENCY',
  ATTACHMENT = 'ATTACHMENT',
  AUTH = 'AUTH',
  SYSTEM = 'SYSTEM',
}
